# Dockerfile para o backend Node.js
FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ENV NODE_ENV=production
ENV DB_HOST=postgres
ENV DB_PORT=5432
ENV DB_USER=matchit
ENV DB_PASSWORD=matchit123
ENV DB_NAME=matchit_db

EXPOSE 3000

CMD ["npm", "start"]